version: '3'
services:
  database:
    image: "postgres" 
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ 
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  database-data: 
