# Generated by Django 4.0.4 on 2022-05-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_user_id', models.CharField(max_length=100)),
                ('timestamp', models.BigIntegerField()),
                ('size', models.BigIntegerField()),
                ('time_backend', models.BigIntegerField()),
                ('status', models.CharField(choices=[('success', 'success'), ('fail', 'fail')], default='success', max_length=7)),
                ('direction', models.CharField(choices=[('upload', 'upload'), ('download', 'download')], default='upload', max_length=8)),
            ],
            options={
                'ordering': ['client_user_id'],
            },
        ),
    ]
